name: Generate
on: [push,workflow_dispatch]

jobs:
  generate:
    name: 'Generate GRPC client'
    runs-on: ubuntu-latest

    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'

      - name: Install dependencies
        run: |
          go get -u -v github.com/golang/protobuf/protoc-gen-go@v1.4.2

          go install -v  \
              "google.golang.org/grpc/cmd/protoc-gen-go-grpc" \
              "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway" \
              "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"

      - name: Checkout Flipt
        uses: actions/checkout@v2
        with:
          repository: markphelps/flipt
          path: tmp/flipt

      - name: Generate Go client
        run: |
          echo "--> generating Go client ..."
          protoc -I tmp/flipt/rpc/ tmp/flipt/rpc/flipt.proto --go_out=plugins=grpc:"."