on:
  workflow_dispatch:

inputs:
  tag:
    required: true
    description: Flipt release version tag to generate

permissions:
  contents: write
  pull-requests: write

name: proto-upgrade
jobs:
  proto-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup go-task/task
        use: 'lagren/setup-task@v1'

      - name: Clone Flipt into sub-directory
        run: gh repo clone flipt-io/flipt

      - name: Bootstrap Tools
        run: |
          pushd ./flipt
          git checkout ${{ inputs.tag }}
          task bootstrap
          popd

      - name: Buf Generate
        run: buf generate

      - name: Remove Flipt
        run: rm -rf ./flipt/

      - name: Prepare Branch
        run: |
          git checkout -b "generate/${{ inputs.tag }}"
          git add .
          git commit -m "feat: updates to protobuf definitions for flipt ${{ inputs.tag }}"
          git push origin "generate/${{ inputs.tag }}"
          gh pr create --fill

